name: SEO
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'url to run test'
        required: true
        default: 'https://b01www.selfridges.com/GB/en/'
      user:
        description: 'User'
        required: true
        default: 'goldtest'
      pass:
        description: 'Pass'
        required: true
        default: ''

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update var
        run: |
          sed -i -e "s|PASS|${{ github.event.inputs.pass }}|g" .github/workflows/login.js
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: npm install, build
        run: |
          npm install puppeteer
          
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            ${{ github.event.inputs.url }}
          configPath: '.github/workflows/lighthouserc.json'
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
