name: Run SEO tests
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'url to run test'
        required: true
        default: 'https://b01www.selfridges.com/GB/en/'
      user:
        description: 'User'
        required: true
        default: 'goldtest'
      pass:
        description: 'Pass'
        required: true
        default: 'g0ld5ive'

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            ${{ inputs.url }}
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
          basicAuthUsername: ${{ inputs.user }}
          basicAuthPassword: ${{ inputs.pass }}
