name: SEO-TEST
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'url to run test'
        required: true
        default: 'https://www.hotnews.ro'
      user:
        description: 'User'
        required: true
        default: 'goldtest'
      pass:
        description: 'Pass'
        required: true
        default: ''

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          npm install && npm install -g @lhci/cli@0.8.x
      - name: login
      - run: lhci collect --url="${{ github.event.inputs.url }}"  numberOfRuns=1
